version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  # node-app:
  #   build:
  #     context: .
  #   container_name: node_app
  #   environment:
  #     CORE_API_URL: ${CORE_API_URL}
  #     APP_PORT: ${APP_PORT}
  #     DB_HOST: postgres
  #     DB_PORT: ${DB_PORT}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}
  #     DB_NAME: ${DB_NAME}
  #     SSL_ENABLED: ${SSL_ENABLED}
  #   ports:
  #     - "${APP_PORT}:3000"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
